### ISSUE TITLE
Error during compilation with TensorRT 8

### ISSUE THREAD

**Issue by sbugallo** [grimoire/amirstan_plugin#20]
Hi!

I'm trying to compile this project with TensorRT 8 but some errors raised because NVIDIA added the noexcept operator to some declarations and also made some methods private. You can find the output log [here](https://github.com/grimoire/amirstan_plugin/files/6868397/log.txt).

is the support for TensorRT 8 on the roadmap?

Thanks!

**Comment by grimoire** [comment]
Hi
I am working on it, might take some time.
If you want to try fix it by yourself, [this issue](https://github.com/open-mmlab/mmcv/issues/1180) might help you.

**Comment by grimoire** [comment]
Update
TensorRT8 is supported now.
Note that I have not yet tested all supported models in [mmdetection-to-tensorrt](https://github.com/grimoire/mmdetection-to-tensorrt). If you meet any problems, please feel free to report here.

**Comment by sbugallo** [comment]
I've been working with this project a few days now and so far so good. I think we can close this issue. Since version 0.4.1 does not include TensorRT 8 support, I hope to see a new release soon! Thanks!!
