### ISSUE TITLE
How to set nms plugin threshold?

### ISSUE THREAD

**Issue by jinfagang** [grimoire/amirstan_plugin#26]
How to set nms plugin threshold?

**Comment by grimoire** [comment]
NMS plugin is created by `BatchedNMSPluginCustomCreator` in [batchedNMSPlugin](https://github.com/grimoire/amirstan_plugin/blob/master/src/plugin/batchedNMSPlugin/batchedNMSPlugin.cpp). You can create it with attributes `PluginFieldCollection`, of cause nms threshold is in it.
If you prefer python api, you can create plugin field collection like [create_batchednms_plugin](https://github.com/grimoire/mmdetection-to-tensorrt/blob/master/mmdet2trt/converters/plugins/create_batchednms_plugin.py) than send the collection to `add_plugin_v2` like [this](https://github.com/grimoire/mmdetection-to-tensorrt/blob/master/mmdet2trt/converters/batched_nms.py)
