### ISSUE TITLE
cmake error:No CMAKE_CUDA_COMPILER could be found.

### ISSUE THREAD

**Issue by JasonDu1993** [grimoire/amirstan_plugin#3]
hello，I have some problem. **CMake Error at src/plugin/CMakeLists.txt:6 (enable_language):**
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_CUDA_COMPILER to the full path to the compiler, or to the compiler
  name if it is in the PATH.

CMake Error: Could not find cmake module file: CMakeCUDAInformation.cmake
CMake Error: CMAKE_CUDA_COMPILER not set, after EnableLanguage

**I can use nvcc** 
root@8c74b39d4dd2:/opt# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

system:ubuntu docker CUDA10.0 cudnn7.4.2

**Comment by JasonDu1993** [comment]
I commend enable_language(CUDA) in all CMakeLists.txt. And change it to below:
find_package(CUDA REQUIRED)
include_directories(SYSTEM ${CUDA_INCLUDE_DIRS})

**Comment by IOEvan** [comment]
I meet the same question. Could you provide the full contexts of your CMakeLists.txt?

**Comment by JasonDu1993** [comment]
> I meet the same question. Could you provide the full contexts of your CMakeLists.txt?

There ars so many CMakeLists.txt files. You can search the key enable_language(CUDA) in CMakeLists.txt, and change it to below:
find_package(CUDA REQUIRED)
include_directories(SYSTEM ${CUDA_INCLUDE_DIRS})

I success it by the way.

**Comment by IOEvan** [comment]
Thanks
