### ISSUE TITLE
NvInferRuntimeCommon.h not find

### ISSUE THREAD

**Issue by JasonDu1993** [grimoire/amirstan_plugin#4]
/opt/amirstan_plugin/src/plugin/common/logging.h:20:10: fatal error: NvInferRuntimeCommon.h: No such file or directory
 #include "NvInferRuntimeCommon.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

detail:
(trt) root@8c74b39d4dd2:/opt/amirstan_plugin/build# make -j10
-- Found TensorRT headers at /usr/include/x86_64-linux-gnu
-- Find TensorRT libs at /usr/lib/x86_64-linux-gnu/libnvinfer.so;/usr/lib/x86_64-linux-gnu/libnvparsers.so;/usr/lib/x86_64-linux-gnu/libnvinfer_plugin.so
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/amirstan_plugin/build
[  1%] Building NVCC (Device) object src/amir_cuda_util/CMakeFiles/amir_cuda_util.dir/amir_cuda_util_generated_repeatDims.cu.o
[  2%] Building NVCC (Device) object src/amir_cuda_util/CMakeFiles/amir_cuda_util.dir/amir_cuda_util_generated_memcpyPermute.cu.o
[  4%] Building NVCC (Device) object src/amir_cuda_util/CMakeFiles/amir_cuda_util.dir/amir_cuda_util_generated_tensorMeanVar.cu.o
Scanning dependencies of target amir_cuda_util
[  5%] Linking CXX static library ../../lib/libamir_cuda_util.a
[  5%] Built target amir_cuda_util
[  7%] Building NVCC (Device) object src/plugin/groupNormPlugin/CMakeFiles/groupNormPlugin_static.dir/groupNormPlugin_static_generated_group_norm_kernel.cu.o
[  8%] Building NVCC (Device) object src/plugin/roiExtractorPlugin/CMakeFiles/roiExtractorPlugin_static.dir/roiExtractorPlugin_static_generated_roi_extractor_kernel.cu.o
Scanning dependencies of target exViewPlugin_static
Scanning dependencies of target repeatDimsPlugin_static
[ 10%] Building NVCC (Device) object src/plugin/delta2bboxPlugin/CMakeFiles/delta2bboxPlugin_static.dir/delta2bboxPlugin_static_generated_delta2bbox.cu.o
[ 11%] Building NVCC (Device) object src/plugin/layerNormPlugin/CMakeFiles/layerNormPlugin_static.dir/layerNormPlugin_static_generated_layer_norm_kernel.cu.o
[ 12%] Building NVCC (Device) object src/plugin/gridAnchorDynamicPlugin/CMakeFiles/gridAnchorDynamicPlugin_static.dir/gridAnchorDynamicPlugin_static_generated_grid_anchor_dynamic.cu.o
[ 14%] Building NVCC (Device) object src/plugin/torchGatherPlugin/CMakeFiles/torchGatherPlugin_static.dir/torchGatherPlugin_static_generated_torch_gather.cu.o
[ 15%] Building NVCC (Device) object src/plugin/deformableConvPlugin/CMakeFiles/deformableConvPlugin_static.dir/deformableConvPlugin_static_generated_deform_conv_cuda_kernel.cu.o
[ 17%] Building NVCC (Device) object src/plugin/batchedNMSPlugin/CMakeFiles/batchedNMSPlugin_static.dir/batchedNMSPlugin_static_generated_sortScoresPerImage.cu.o
[ 18%] Building CXX object src/plugin/exViewPlugin/CMakeFiles/exViewPlugin_static.dir/exViewPlugin.cpp.o
[ 20%] Building CXX object src/plugin/repeatDimsPlugin/CMakeFiles/repeatDimsPlugin_static.dir/repeatDimsPlugin.cpp.o
In file included from /opt/amirstan_plugin/src/plugin/common/logger.h:20:0,
                 from /opt/amirstan_plugin/src/plugin/common/common.h:32,
                 from /opt/amirstan_plugin/src/plugin/exViewPlugin/exViewPlugin.cpp:5:
/opt/amirstan_plugin/src/plugin/common/logging.h:20:10: fatal error: NvInferRuntimeCommon.h: No such file or directory
 #include "NvInferRuntimeCommon.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/plugin/exViewPlugin/CMakeFiles/exViewPlugin_static.dir/build.make:62: recipe for target 'src/plugin/exViewPlugin/CMakeFiles/exViewPlugin_static.dir/exViewPlugin.cpp.o' failed
make[2]: *** [src/plugin/exViewPlugin/CMakeFiles/exViewPlugin_static.dir/exViewPlugin.cpp.o] Error 1
CMakeFiles/Makefile2:430: recipe for target 'src/plugin/exViewPlugin/CMakeFiles/exViewPlugin_static.dir/all' failed
make[1]: *** [src/plugin/exViewPlugin/CMakeFiles/exViewPlugin_static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by grimoire** [comment]
Hi
please check if you have set TENSORRT_ROOT path in CMakeLists.txt

**Comment by JasonDu1993** [comment]
> Hi
> please check if you have set TENSORRT_ROOT path in CMakeLists.txt

 (trt) root@8c74b39d4dd2:/opt/amirstan_plugin/build# cmake ..
......
-- Found TensorRT headers at /usr/include/x86_64-linux-gnu
-- Find TensorRT libs at /usr/lib/x86_64-linux-gnu/libnvinfer.so;/usr/lib/x86_64-linux-gnu/libnvparsers.so;/usr/lib/x86_64-linux-gnu/libnvinfer_plugin.so
-- Found TENSORRT: /usr/include/x86_64-linux-gnu

my tensorrt version is 7.0.0.11

**Comment by grimoire** [comment]
Try change 
`INCLUDE_DIRECTORIES(${TENSORRT_ROOT}/include)`
to
`INCLUDE_DIRECTORIES(${TENSORRT_INCLUDE_DIR})`

see if it works.

**Comment by JasonDu1993** [comment]
> Try change
> `INCLUDE_DIRECTORIES(${TENSORRT_ROOT}/include)`
> to
> `INCLUDE_DIRECTORIES(${TENSORRT_INCLUDE_DIR})`
> 
> see if it works.

Thanks，Isuccess. I change the CUB_ROOT_DIR and TENSORRT_ROOT to my dir.
eset(CUB_ROOT_DIR "/opt/cub-1.8.0")
set(TENSORRT_ROOT "/opt/TensorRT-7.0.0.11")
the cub-1.8.0 link: https://github.com/NVlabs/cub/releases, I download https://github.com/NVlabs/cub/releases/tag/v1.8.0

**Comment by grimoire** [comment]
Congratulation
I will optimize install script in future. Make the installation much easier.
