### ISSUE TITLE
About using BatchNMSPlugin when embed plugin to custom built network INetworkDefinition

### ISSUE THREAD

**Issue by osirisQdt** [grimoire/amirstan_plugin#40]
Hi @grimoire ,
I'm trying to deploy a custom Faster-RCNN network from scratch using TensorRT C++ API (using INetworkDefinition API). I'm stucking to step implementing batch non-maximum-suppression in Region Proposal Network and found out your NMS Plugin. So, I wanna embed your plugin to my network, but couldn't understand input and output of your plugin. So could you explain more clearly about plugin?
Thanks for reading my post, very glad to hear your response from you.
Best regards

**Comment by grimoire** [comment]
Hi, sorry for the late reply.

The inputs should have shapes:
- boxes: `[batch_size, num_boxes, num_classes, 4]`, the input boxes of each classes, `num_classes` could be 1 if `shareLocation` is enabled
- score: `[batch_size, num_boxes, num_classes]` the scores of each boxes

attributes are scalars with types:
https://github.com/grimoire/mmdetection-to-tensorrt/blob/master/mmdet2trt/converters/plugins/create_batchednms_plugin.py

There are 4 outputs
- num_boxes: `[batch_size, 1]`, the output boxes numbers
- score: `[batch_size, num_boxes]` the output scores of each boxes
- boxes: `[batch_size, num_boxes, 4]` The valid boxes after nms
- class_id: `batch_size, num_boxes]`, The class type id of each boxes

Here is an example to build the layer with inetwork. hope this can help you
https://github.com/grimoire/mmdetection-to-tensorrt/blob/master/mmdet2trt/converters/batched_nms.py

**Comment by grimoire** [comment]
This plugin is modified from [the official one](https://github.com/NVIDIA/TensorRT/tree/release/8.6/plugin/batchedNMSPlugin) in TensorRT 7.0, they might have a better implementation now. It would be a good idea to try that plugin.

**Comment by osirisQdt** [comment]
> This plugin is modified from [the official one](https://github.com/NVIDIA/TensorRT/tree/release/8.6/plugin/batchedNMSPlugin) in TensorRT 7.0, they might have a better implementation now. It would be a good idea to try that plugin.

Thanks for your response. I'll try the plugin.
