### ISSUE TITLE
cub >= 1.8.0 install 

### ISSUE THREAD

**Issue by KevenLee** [grimoire/amirstan_plugin#5]
Thanks for your jobs. But I found no instruction to install cub in "https://nvlabs.github.io/cub/". Could you help me.

Thanks.

**Comment by grimoire** [comment]
Hi,
Download and unarchive the package is enough.

**Comment by KevenLee** [comment]
> Hi,
> Download and unarchive the package is enough.

OK, I done it. Thanks
