### ISSUE TITLE
need to install deepstream

### ISSUE THREAD

**Issue by lexiqi** [grimoire/amirstan_plugin#6]
hi, I want to make sure that need to install deepstream?? Tks
![image](https://user-images.githubusercontent.com/25817952/95733686-0fe1c400-0cb5-11eb-9704-6406c89dc92b.png)

**Comment by grimoire** [comment]
Hi 
deepstream support is an optional.
If you do need use the detection model created by [mmdetection-to-tensorrt](https://github.com/grimoire/mmdetection-to-tensorrt), you can cmake like this:
```
cmake ...... -DWITH_DEEPSTREAM=true -DDeepStream_DIR=<path/to/deepstream> .....
```
to enable deepstream support. 

If you does not need it. just ignore the log.

**Comment by lexiqi** [comment]
> Hi
> deepstream support is an optional config.
> If you want to use the detection model created by [mmdetection-to-tensorrt](https://github.com/grimoire/mmdetection-to-tensorrt) in deepstream, you can cmake like this:
> 
> ```
> cmake ...... -DWITH_DEEPSTREAM=true -DDeepStream_DIR=<path/to/deepstream> .....
> ```
> 
> to enable deepstream support.
> 
> If you does not need it. just ignore the log.

get,,,thank you~
